backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "articole"
    label: "Articole"
    folder: "articles"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titlu", name: "title", widget: "string"}
      - {label: "Categorie", name: "cat", widget: "select", options: ["Politică", "Economie", "Societate", "Tehnologie", "Externe"]}
      - {label: "Descriere scurtă", name: "dek", widget: "text"}
      - {label: "Oraș", name: "place", widget: "string"}
      - {label: "Autor", name: "author", widget: "string", default: "Redacția"}
      - {label: "Etichetă (opțional)", name: "tag", widget: "string", required: false}
      - {label: "Data", name: "date", widget: "datetime"}
